### ISSUE TITLE
WIFI dongle support

### ISSUE THREAD

**Issue by jerson** [ayufan-rock64/android-7.1#1]
is it possible to add support for WiFi dongle?

https://www.pine64.org/?product=usb-wifi-802-11bgn-rtl8188eu-for-rock64

**Comment by ayufan** [comment]
This one is definitely supported by my Android TV build, as I'm using it myself.

**Comment by post2skumar** [comment]
Sorry for opening the old thread. I have the same WiFi dongle mentioned by Jerson. 

https://www.pine64.org/?product=usb-wifi-802-11bgn-rtl8188eu-for-rock64

I have installed "android-7.1-rock-64-rock64_atv-v0.3.11-r108-update.zip", but the dongle is not recognized.

**Comment by interfect** [comment]
I have that dongle too; it is not working for me in `android-7.1-rock-64-rock64_atv-v0.3.4-r86-raw.img.gz`, the current stable release. When I turn on wifi in the settings it just turns itself back off, and I can't see any networks.
