### ISSUE TITLE
Issue with sound

### ISSUE THREAD

**Issue by droidforever** [ayufan-rock64/android-7.1#11]
I installed your android tv rom on the rock64 and then did a channel scan.  I use an HDHomerun for live tv.  It completed the scan fine but the sound is just a static buzz.  Is there a fix or do I need to wait for your next release.  
I used the Pine64 installer I also tried Etcher.  I am running on a Samsung Evo 64GB SD card.

Thank you for your reply.

**Comment by rmrten** [comment]
did you resolved it? have the same issue with rock64 and multiple OS version installed on board. Using Samsung Evo card
