### ISSUE TITLE
Google Cast Receiver

### ISSUE THREAD

**Issue by Kunibert-007** [ayufan-rock64/android-7.1#28]
Would like to cast media-content like Youtube to the Android TV but after installing the Google-Cast-Receiver-APK-File I don't see the Android TV on my smartphone as cast-receiver.

**Comment by ayufan** [comment]
It will not happen. Google Cast requires a Google Provisioned certificate preloaded by the manufacturer.

**Comment by riverpro13** [comment]
I am using android tv on the rock64  sign into utube on the rock64 and you
will have utube running to your hearts content  it is excellent I run it
almost 24 / 7   with no problems
