### ISSUE TITLE
Google Cast Compatibility

### ISSUE THREAD

**Issue by albydnc** [ayufan-rock64/android-7.1#29]
As an android TV I was expecting the oob compatibility with Google Cast, but I can't see it. Do I have to activate it? Or it isn't present? Neither Google home mini nor my phone can see it.

**Comment by LennyPenny** [comment]
Same problem here, any ideas?

**Comment by ptoulza** [comment]
Ayufan already replied to this : https://github.com/ayufan-rock64/android-7.1/issues/28
Google cast will probably never work on this build.

**Comment by ayufan** [comment]
Yes. If you want google cast just buy mibox3.

**Comment by ayufan** [comment]
It sells for around $50 from gearbest.
