### ISSUE TITLE
Freezes during boot or Leanback Launcher stopped

### ISSUE THREAD

**Issue by droidforever** [ayufan-rock64/android-7.1#4]
I just got my Rock64 4GB board with a 64GB eMMC.  I am using Android Tool and the android-7.1-rock-64-rock64_atv-v0.3.4-r86-update image file.  I have re-imaged this several times.  I either get a frozen screen during "Preparing recommendations"  or I get a "Leanback launcher has stopped" and then it freezes.  I have no idea what I am doing wrong.  I install and then wait 30 minutes for the OS to boot.  When I return to view the desktop it is frozen or just says "android".  Any assistance is greatly appreciated.  Thank you.

**Comment by ayufan** [comment]
Strange. I don't see that problem. Can you write eMMC chip model?

**Comment by droidforever** [comment]
The imprint of the numbers is so small I am not sure I am getting this right but it's a Sandisc it looks like SUINAOFA 64S
I bought this on the Pine64 site as an eMMC for the rock64

**Comment by ayufan** [comment]
Use phone camera with flash.

Try also writing to good SD card like EVO/+.

**Comment by droidforever** [comment]
I did and enhanced it and enlarged it.  SDINADF4-64G is the correct number on the chip.

**Comment by droidforever** [comment]
I used Etcher instead of Android Tool and this time I was successful writing to the eMMC using a USB SD card reader and a SD to eMMC adaptor.  Thank you for all your assistance and your tremendous development!!! :)

**Comment by ayufan** [comment]
Does it work?

**Comment by droidforever** [comment]
As soon as I hooked up my DAC board and ran spidf out it started freezing again.

**Comment by droidforever** [comment]
I re-imaged the chip again and it booted and the DAC is functioning.  I'm afraid to close this just yet as I suspect it might happen again.  But for now it is functioning.

**Comment by droidforever** [comment]
Other than Kodi Krypton continually freezing and crashing everything so far so good.  Should I remove Kodi and use OSMC instead?  I just want to make sure my dolby atmos audio and my HDR10 video play clean. on my Samsung 4K HDR10 Television.

**Comment by ayufan** [comment]
Trzy vlc

**Comment by droidforever** [comment]
I think I am going to give up.  It's still periodically freezing and I'm unable to watch my 4K movies They constantly buffer.  I don't believe the board can handle the auidio throughput as it is 10bit Dolby Atmos.  I'll find another use for this board.  Thank you for all willingness to assist me.  You are a tribute to the community.

**Comment by ayufan** [comment]
@rock64-linux can you help?

**Comment by droidforever** [comment]
all assistance would be appreciated.  Kodi continues to crash freezing the OS and causing me to have to reboot with the reset switch.  Kodi is my main reason for using this and the RKMC is version 16 while I am using 17.4 on all my other devices.

**Comment by droidforever** [comment]
Do you have any 64 bit Linux Releases with Desktops either Debian or Stretch?

**Comment by ayufan** [comment]
Nope

**Comment by pgmy64** [comment]
For 4K Playback, it is better to use RKMC as Rockchip still not yet fully optimize their playback engine for KODI 17.4

**Comment by droidforever** [comment]
Thank you I have switched to RKMC.  But Kodi 16 is quite outdated now.
